jobprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('candidate/', include('candidate.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register', UserCreateView.as_view(), name='register'),
    path('home', HomeView.as_view(), name='home'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', logout_user.as_view(), name='logout'),
    path('managerCreate', AssignManagerView.as_view(), name='managerCreate'),
    path('manager-list', ManagerList.as_view(), name='manager-list'),
    path('agent-assign', AssignAgentView.as_view(), name='agent-assign'),
    path('agent-list', AgentList.as_view(), name='agent-list'),
    path('candidate', CandidateRequestView.as_view(), name='candidate-list'),
    path('download/<int:pk>', download_file.as_view(), name='download'),
    path('candidate/update/<int:pk>', CandidateRequestUpdate.as_view(), name='candidate-update'),

    # path('admin-show-request/', AdminShowRequest.as_view(), name='admin-show-request'),
    # path('allagentshow/<int:pk>', AdminShowAgent.as_view(), name='All-agent'),
    # path('allrequest-agent/<int:pk>', ShowAllRequestAdmin.as_view(), name='allrequest-agent')

    path('admin-show-request/', AdminAllRequest.as_view(), name='admin-show-request'),

]

templates/page/admin_request.html
{% extends 'base.html' %}
{% block title %} Total request{% endblock %}
{% block pagecontent %}

<!--<div class="container">-->
<!--    <h3>Total Request</h3>-->
<!--    <table class="table">-->
<!--        <thead class="thead-dark">-->
<!--        <tr>-->
<!--            <th scope="col">Id</th>-->
<!--            <th scope="col">Manager</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        {% for manager in managers %}-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th scope="col">{{forloop.counter}}</th>-->
<!--            <th scope="col"><a href="#">{{manager.user}}</a></th>-->
<!--            {% for agent in agent_list%}-->
<!--        <tr>-->
<!--            <th scope="col">{{forloop.counter}}</th>-->
<!--            <th scope="col"><a href="#">{{agent}}</a></th>-->
<!--        </tr>-->
<!--        {% endfor %}-->
<!--        </tr>-->
<!--        {% for candidate in candidates %}-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th scope="col">{{forloop.counter}}</th>-->
<!--            <th scope="col">{{candidacounterte.created}}</th>-->
<!--            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>-->
<!--            <th scope="col">{{candidate.mobile_no}}</th>-->
<!--            <th scope="col">{{candidate.email}}</th>-->
<!--            <th scope="col">{{candidate.gender}}</th>-->
<!--            <th scope="col">{{candidate.reference_details}}</th>-->
<!--            <th scope="col"><a href="{% url 'users:download' candidate.pk %}"><i class="fa fa-download" aria-hidden="true"></i></a>-->
<!--            </th>-->
<!--            <th scope="col">{{candidate.profile_status}}</th>-->
<!--            <th scope="col"><a href="{% url 'users:candidate-update' candidate.pk %}">Open</a></th>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--        {% endfor %}-->
<!--        </tbody>-->
<!--        {% endfor %}-->
<!--        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>-->
<!--    </table>-->
<!--</div>-->
{% block head %}
<style>
    .dropdown-menu {
        width: 100%;
        left: 0;
        right: 0;
        border-radius: 0;
    }

</style>
{% endblock %}

<h3>Show Request</h3>

<ul>
    {% for manager, agent in data.items %}
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false" style="width: 100%; margin: 10px 0; padding: 10px; ">
            {{ manager }}
        </button>
        <!--        <li class="dropdown-item" style="color:blue">{{ manager }}</li>-->
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% for agent , candidates in agent.items %}
            <li class="dropdown-item dropdown-toggle" id="multilevelDropdownMenu1" data-bs-toggle="dropdown"
                aria-expanded="false">{{ agent }}
            </li>
            <ul class="dropdown-menu" aria-labelledby="multilevelDropdownMenu1">
                {% for candidate in candidates %}
                <ul class="dropdown-tem">
                    <p>ID: {{ candidate.id }}</p>
                    <p>Name: {{ candidate.name }}</p>
                    <p>Last Name: {{ candidate.last_name }}</p>
                </ul><hr>
                {% empty %}
                <li>No candidates for this agent</li>
                {% endfor %}
            </ul>
            {% empty %}
            <li>No agents for this manager</li>
            {% endfor %}
        </ul>
        {% empty %}
        <li>No managers found</li>
        {% endfor %}
    </div>
</ul>

<script>
    let dropdowns = document.querySelectorAll('.dropdown-toggle')
    dropdowns.forEach((dd)=>{
    dd.addEventListener('click', function (e) {
        var el = this.nextElementSibling
        el.style.display = el.style.display==='block'?'none':'block'
    })
})
</script>


{% endblock %}

templates/page/agent_assign.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Assign agent {% endblock %}
{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<form method="POST" novalidate>{% csrf_token %}
    <h3>Assign Agent</h3>
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

templates/page/agent_list.html
{% extends 'base.html' %}
{% block title %} Agent List{% endblock %}
{% block pagecontent %}

<div class="container">
    <h3>Agent List</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Agent</th>
            <th scope="col">Code</th>
        </tr>
        </thead>
        <tbody>
        {% for agent in object_list %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{agent.user}}</th>
            <th scope="col">{{agent.code}}</th>
        </tr>
        </tbody>
        {% endfor %}
        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
        </tbody>
    </table>
</div>

{% endblock %}

templates/page/candidate_profile_update.html
{% extends 'base.html' %}
{% block title %} Candidate Request Update{% endblock %}
{% block pagecontent %}


{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
  <div class="container col-sm-10">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-outline-success"> Update Profile</button>
    <a type="submit" class="btn btn-outline-danger" href="{% url 'users:home' %}"> Cancel</a>
  </div>
</form>
{% endblock %}

templates/page/candidate_request.html
{% extends 'base.html' %}
{% block title %} Candidate Request{% endblock %}
{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}


<div class="container">
    <h3>Candidate Request List</h3>
    {% if request.user.is_manager %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Create Date</th>
            <th scope="col">Name</th>
            <th scope="col">Mobile No</th>
            <th scope="col">Email</th>
            <th scope="col">Gender</th>
            <th scope="col">Agent Code</th>
            <th scope="col">Resume</th>
            <th scope="col">Status</th>
            <th> Action</th>
        </tr>
        </thead>

        {% for candidate in all_agent_candidates %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{candidate.created}}</th>
            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>
            <th scope="col">{{candidate.mobile_no}}</th>
            <th scope="col">{{candidate.email}}</th>
            <th scope="col">{{candidate.gender}}</th>
            <th scope="col">{{candidate.reference_details}}</th>
            <th scope="col"><a href="{% url 'users:download' candidate.pk %}"><i class="fa fa-download"
                                                                                 aria-hidden="true"></i></a>
            </th>
            <th scope="col">{{candidate.profile_status}}</th>
            <th scope="col"><a href="{% url 'users:candidate-update' candidate.pk %}">Open</a></th>
        </tr>
        </tbody>
        {% endfor %}

        <!--        {% for candidate in other %}-->
        <!--        <tbody>-->

        <!--        <tr>-->
        <!--            <th scope="col">{{forloop.counter}}</th>-->
        <!--            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>-->
        <!--            <th scope="col">{{candidate.mobile_no}}</th>-->
        <!--            <th scope="col">{{candidate.reference}}</th>-->
        <!--            <th scope="col">{{candidate.profile_status}}</th>-->
        <!--        </tr>-->
        <!--        </tbody>-->
        <!--        {% endfor %}-->

        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
        </tbody>
    </table>
    <br>

    <table class="table">
        <h3>Social Request</h3>
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Mobile No</th>
            <th scope="col">Reference Details</th>
            <th scope="col">Status</th>
        </tr>
        </thead>

        {% for candidate in other %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>
            <th scope="col">{{candidate.mobile_no}}</th>
            <th scope="col">{{candidate.reference}}</th>
            <th scope="col">{{candidate.profile_status}}</th>
        </tr>
        </tbody>
        {% endfor %}
        <!--        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>-->
        </tbody>
    </table>


    {% elif request.user.is_agent %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Create Date</th>
            <th scope="col">Name</th>
        </tr>
        </thead>

        {% for candidate in candidates %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{candidate.created}}</th>
            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>
        </tr>
        </tbody>
        {% endfor %}
        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
    </table>
    {% endif %}
</div>
{% endblock %}

templates/page/manager_list.html
{% extends 'base.html' %}
{% block title %} Manager List{% endblock %}
{% block pagecontent %}

<div class="container">
    <h3>Manager List</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Manager</th>
        </tr>
        </thead>
        <tbody>
        {% for manager in object_list %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{manager.user}}</th>

        </tr>
        </tbody>
        {% endfor %}
        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
        </tbody>
    </table>
</div>

{% endblock %}

templates/page/managercreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Manager create{% endblock %}
{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<form method="POST" novalidate>{% csrf_token %}
    <h3>Create Manager</h3>
    {{form.as_p}}
<!--    <div class="mb-3">-->
<!--        <label for="exampleInputEmail1" class="form-label">Users</label>-->
<!--        {{form.user}}-->
<!--&lt;!&ndash;        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">&ndash;&gt;-->
<!--        &lt;!&ndash;        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>&ndash;&gt;-->
<!--    </div>-->
<!--    &lt;!&ndash;    <div class="mb-3">&ndash;&gt;-->
<!--    &lt;!&ndash;        <label for="exampleInputPassword1" class="form-label">Password</label>&ndash;&gt;-->
<!--    &lt;!&ndash;        <input type="password" class="form-control" id="exampleInputPassword1">&ndash;&gt;-->
<!--    &lt;!&ndash;    </div>&ndash;&gt;-->
<!--    <div class="mb-3 form-check">-->
<!--        <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
<!--        <label class="form-check-label" for="exampleCheck1">is_manager</label>-->
<!--    </div>-->
<!--    <div class="mb-3 form-check">-->
<!--        <input type="checkbox" class="form-check-input" id="exampleCheck2">-->
<!--        <label class="form-check-label" for="exampleCheck1">is_agent</label>-->
<!--    </div>-->
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

templates/page/show_agent.html
{% extends 'base.html' %}
{% block title %} Manager List{% endblock %}
{% block pagecontent %}

<div class="container">
    <h3>All Agent request</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Agent</th>
        </tr>
        </thead>
        {% for agent in all_agent %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col"><a href="{% url 'users:allrequest-agent' agent.pk %}">{{agent.user}}</a></th>
        </tbody>
        {% endfor %}
        </tr>

        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
        <a class="btn btn-outline-secondary" href="{% url 'users:admin-show-request' %}"> Back</a>
    </table>
</div>

{% endblock %}

templates/page/show_all_agent_request_admin.html
{% extends 'base.html' %}
{% block title %} Candidate Request{% endblock %}
{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}


<div class="container">
    <h3>Candidate Request List</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Create Date</th>
            <th scope="col">Name</th>
            <th scope="col">Mobile No</th>
            <th scope="col">Email</th>
            <th scope="col">Gender</th>
            <th scope="col">Agent Code</th>
            <th scope="col">Resume</th>
            <th scope="col">Status</th>
            <th> Action</th>
        </tr>
        </thead>

        {% for candidate in candidates %}
        <tbody>
        <tr>
            <th scope="col">{{forloop.counter}}</th>
            <th scope="col">{{candidacounterte.created}}</th>
            <th scope="col">{{candidate.name}} {{candidate.last_name}}</th>
            <th scope="col">{{candidate.mobile_no}}</th>
            <th scope="col">{{candidate.email}}</th>
            <th scope="col">{{candidate.gender}}</th>
            <th scope="col">{{candidate.reference_details}}</th>
            <th scope="col"><a href="{% url 'users:download' candidate.pk %}"><i class="fa fa-download"
                                                                                 aria-hidden="true"></i></a>
            </th>
            <th scope="col">{{candidate.profile_status}}</th>
            <th scope="col"><a href="{% url 'users:candidate-update' candidate.pk %}">Open</a></th>
        </tr>
        </tbody>
        {% endfor %}
        <a class="btn btn-outline-secondary" href="{% url 'users:home' %}"> Main Page</a>
    </table>
</div>
{% endblock %}