candidate/urls.py
from django.urls import path
from . import views

app_name = 'candidate'

urlpatterns = [
    path('form', views.CreateCandidateProfile.as_view(), name='form')
]

jobprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('candidate/', include('candidate.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register', UserCreateView.as_view(), name='register'),
    path('home', HomeView.as_view(), name='home'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', logout_user.as_view(), name='logout'),
    path('managerCreate', AssignManagerView.as_view(), name='managerCreate'),
    path('manager-list', ManagerList.as_view(), name='manager-list'),
    path('agent-assign', AssignAgentView.as_view(), name='agent-assign'),
    path('agent-list', AgentList.as_view(), name='agent-list'),
    path('candidate', CandidateRequestView.as_view(), name='candidate-list'),
    path('download/<int:pk>', download_file.as_view(), name='download'),
    path('candidate/update/<int:pk>', CandidateRequestUpdate.as_view(), name='candidate-update'),

    # path('admin-show-request/', AdminShowRequest.as_view(), name='admin-show-request'),
    # path('allagentshow/<int:pk>', AdminShowAgent.as_view(), name='All-agent'),
    # path('allrequest-agent/<int:pk>', ShowAllRequestAdmin.as_view(), name='allrequest-agent')

    path('admin-show-request/', AdminAllRequest.as_view(), name='admin-show-request'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% block head %} {% endblock %}
</head>
<body>
<!-- header start -->
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <a href="" class="navbar-brand text font-weight-bold text-warning">
            JobProfile
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#myMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="myMenu">
            <ul class="navbar-nav ml-auto ">
                <li class="nav-item"><a href="{% url 'users:home'%}" class="nav-link ">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link ">About</a></li>
<!--                <li class="nav-item dropdown ml-auto">-->
<!--                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"-->
<!--                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Student</a>-->
<!--                    <div class="dropdown-menu ml-auto" aria-labelledby="navbarDropdown">-->
<!--                        <a class="dropdown-item" href="">Student Form</a>-->
<!--                        <a class="dropdown-item" href="">Student List </a>-->
<!--                    </div>-->
<!--                </li>-->
<!--                <li class="nav-item"><a href="#" class="nav-link ">About</a></li>-->
                <li class="nav-item"><a href="#" class="nav-link ">Myprofile</a></li>

                {% if user.is_authenticated %}
                <div class="nav-item dropdown">
                <a href=""  data-toggle="dropdown" class="nav-item nav-link dropdown-toggle user-action">{{user.username}}</a>
                <div class="dropdown-menu">
                    <a href="{% url 'users:logout'%}" class="dropdown-item"><i class="material-icons"></i>Logout</a>
                </div>
                </div>
                {% else %}
                <div class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" class="nav-item nav-link dropdown-toggle user-action"> Login <b class="caret"></b></a>
                    <div class="dropdown-menu">
                        <a href="{% url 'users:login'%}" class="dropdown-item"><i class="fa fa-user-o"></i> Login</a>
                        <a href="{% url 'users:register'%}" class="dropdown-item"><i class="fa fa-calendar-o"></i> SignUp</a>
                    </div>
                </div>
                {% endif %}

            </ul>
        </div>
    </nav>
</header>
<!--Header Over -->

<div class="container mt-4 mb-5">
    {% block pagecontent %}
    {% endblock %}
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous">
</script>
</body>

</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Candidate profile {% endblock %}

<script>
    .hidden{
        display: None
    }

</script>

{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="default-form-list" class="form-group">
        <h5><b>Personal details</b></h5>
        {{ form.as_p}}
    </div>
    <div id="study-form" class="hidden">
        <h5><b>Study details</b></h5>
        {{ candidate_study.as_p }}
    </div>
<!--    <button id="add-more" type="button">Add more</button>-->
    <h5><b>Experience details</b></h5>
        {{ candidate_experience.as_p }}
        <h5><b>Skill details</b></h5>
        {{ candidate_skill.as_p }}
    <button type="submit">Submit</button>
</form>

<script>
    const addMoreBtn = document.getElementById('add-more')
    addMoreBtn.addEventListener('click', add_new_form)
    function add_new_form(event){
        if (event) {
            event.preventDefault()
        }
<!--        const currentForm = document.getElementByClassName('form-group')-->
<!--        const currentForm = currentForm.length-->
        const formCopTarget = document.getElementById('default-form-list')
        const emptyFormEl = document.getElementById('study-form').cloneNode(true)
        emptyFormEl.setAttribute('class', 'form-group')
        emptyFormEl.setAttribute('id', '')
        formCopTarget.append(emptyFormEl)

    }
</script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}
{% block pagecontent %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

{% if request.user.is_superuser %}
<h3>Welcome, Admin {{user.username|title}}</h3>
<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:managerCreate'%}" class="btn btn-secondary">Assign Maneger</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:manager-list'%}" class="btn btn-secondary">Manager List</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="#" class="btn btn-secondary">Create User</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:admin-show-request'%}" class="btn btn-secondary">Total Request</a>
</div>


{% elif request.user.is_manager %}
<h3>Welcome, Manager {{user.username|title}}</h3>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:agent-assign'%}" class="btn btn-secondary">Assign Agent</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:agent-list'%}" class="btn btn-secondary">Agent List</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="#" class="btn btn-secondary">Create User</a>
</div>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:candidate-list'%}" class="btn btn-secondary">Total Request</a>
</div>


{% elif request.user.is_agent %}
<h3>Welcome, Agent {{user.username|title}}</h3>

<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'users:candidate-list'%}" class="btn btn-secondary">Total Request</a>
</div>


{% else %}
<h3>Upload Profile for Candidate </h3>
<div class="mt-4 pt-2">
<!--    <input class="btn btn-primary " type="submit" value="Submit"/>-->
    <a href="{% url 'candidate:form'%}" class="btn btn-secondary">Upload Profile</a>
</div>
{% endif %}
{% endblock %}